"""followers

Revision ID: 262abc7d274b
Revises: 050afcc12b9f
Create Date: 2023-05-30 14:19:34.349948

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '262abc7d274b'
down_revision = '050afcc12b9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
